### ISSUE TITLE
Issue adding product to cart

### ISSUE THREAD

**Issue by MatthewWaite** [QuintinAdam/spree_flexi_variants#15]
Having an issue adding a product with customizations to the cart. 

NoMethodError in Spree::OrdersController#populate
undefined method `first' for #<Spree::ProductCustomization:0x007f96db137e68>

<div class="source " id="frame-source-0">
      <div class="info">
        Extracted source (around line <strong>#433</strong>):
      </div>
      <div class="data">
        <table cellpadding="0" cellspacing="0" class="lines">
          <tbody><tr>
            <td>
              <pre class="line_numbers"><span>431</span>
<span>432</span>
<span>433</span>
<span>434</span>
<span>435</span>
<span>436</span>
              </pre>
            </td>
<td width="100%">
<pre><div class="line">      else
</div><div class="line">        match = matched_attribute_method(method.to_s)
</div><div class="line active">        match ? attribute_missing(match, *args, &amp;block) : super
</div><div class="line">      end
</div><div class="line">    end
</div><div class="line">
</div>
</pre>
</td>
          </tr>
        </tbody></table>
      </div>
    </div>

**Comment by QuintinAdam** [comment]
Spree version? if it is spree 3.4 try this branch https://github.com/gcmartins93/spree_flexi_variants

**Comment by QuintinAdam** [comment]
Changes are now in master or branch spree-3-3
