### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: option[value=]

### ISSUE THREAD

**Issue by uzaif313** [QuintinAdam/spree_flexi_variants#2]
> Uncaught Error: Syntax error, unrecognized expression: option[value=]

This JS error visible while using multiple variant on product page

**Comment by QuintinAdam** [comment]
I'll take a look. What version of spree are you using? 3.0.0? 

If you could provide more information about what type of variants you are using that would be helpful.

**Comment by uzaif313** [comment]
i am using spree 3 and i fixed this bug check my forked repo

**Comment by uzaif313** [comment]
how can i add backside variant in product??
